---
- name: install nginx on CentOs
  yum: name=nginx state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'

- name: install nginx on Ubuntu
  apt: name=nginx state=present
  when: ansible_distribution == 'Ubuntu'

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  #when: packer_builder_type == "amazon-ebs"
  when: packer_builder_type != "docker"
