---
- name: install centos dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - curl
    - htop
    - nmap
    - telnet
    - wget
    - stress
  #when: ansible_distribution == 'CentOS' and "ansible_distribution_version" == "7.0"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'

- name: install Ubuntu dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - curl
    - htop
    - nmap
    - telnet
    - wget
    - stress
  when: ansible_distribution == 'Ubuntu'
